### ISSUE TITLE
请问, FGO NA 是否可以解锁FPS?

### ISSUE THREAD

**Issue by LaughLoaf** [nishuoshenme/fgoUnlockFPS#11]
英服玩家想问一问, FGO NA 能不能解锁 60 FPS? 如果能, 是使用哪种方法? 多谢

**Comment by hexstr** [comment]
没研究过，如果没有加密而且更新过引擎的话，把源代码中的包名换一下就行(大概

**Comment by LaughLoaf** [comment]
英服引擎还没更新, 还是 Unity 5. 是否能更改BGO的源代码包名? 也想问, BGO包名是不是在 other.cpp?

**Comment by hexstr** [comment]
> 英服引擎还没更新, 还是 Unity 5. 是否能更改BGO的源代码包名? 也想问, BGO包名是不是在 other.cpp?

和以前日服一样的加密，每个版本都要更新地址，没救

**Comment by LaughLoaf** [comment]
啊 明白了, 多谢指教

**Comment by hexstr** [comment]
> 啊 明白了, 多谢指教

看来是我把问题想复杂了。先刷`Magisk-riru`然后[下载这个](https://github.com/nishuoshenme/FGOFPSUnlocker/releases/tag/fgo.en)刷入试试
![20191110163012](https://user-images.githubusercontent.com/28940831/68541213-a340b400-03d7-11ea-824f-baf6155ddeda.jpg)

**Comment by LaughLoaf** [comment]
哇, 测试了一下, 成功了。真是厉害, 非常感谢!
