### ISSUE TITLE
FGO NA 60FPS 方式？

### ISSUE THREAD

**Issue by Vacuumvoid** [nishuoshenme/fgoUnlockFPS#12]
大神你好，
之前也看到过#11但是因为我大部分是在模拟器上玩，所以一听要装Magisk就没辙了。
请问一下有没有可用il2cppdumper方式而获取美服60FPS的方案/教程？
加上我觉得更改文件的方式还是比较方便的，因为我有两台小米手机，一台有root另外一台没有，把文件上传到root的那台后，可用 小米换机 把App里所有的资料转到无root的那台上然后再玩。
求求大神能指点指点🙏

**Comment by hexstr** [comment]
> 有没有可用il2cppdumper方式而获取美服60FPS的方案/教程？

都是一样的，如果美服也是用了新版本编译，有`libil2cpp.so`这个文件的话
> 大部分是在模拟器上玩  

模拟器用`xposed`吧，如果没有检测的话

**Comment by Vacuumvoid** [comment]
那个美服的目录结构好像不一样，
![image](https://user-images.githubusercontent.com/24909782/79060990-b9c4a180-7cce-11ea-98a5-d9eba8879c3c.png)
而且也查过了`libil2cpp.so`这个文件在美服上不存在 😢

还有就是美服不服root，只要探测到系统有root就闪退

**Comment by hexstr** [comment]
那没办法，还是旧版的

**Comment by Vacuumvoid** [comment]
那么请问下记不记得B服是什么时候更新到新版的呢？

**Comment by hexstr** [comment]
b服也是旧版，只不过自己加上了开关

**Comment by Vacuumvoid** [comment]
那我在模拟器上试试Xposed吧，那个Emulator Module能在美服上用吗？

**Comment by hexstr** [comment]
美服的xposed模块我好像删了(或者压根没做)，然后就是有root和xpoded检测的。你用的哪个模拟器？

**Comment by Vacuumvoid** [comment]
🤔
那么我觉得没辙了。之前一直在用夜神，可是后来在MuMu上玩了一会儿一升级后就又闪退了，现在又回到夜神了，我有点好奇当时MuMu是怎么做到60FPS的

**Comment by hexstr** [comment]
看我[这篇博客](https://blog.palug.cn/2634.html)吧，你考虑是降级mumu还是和我一样换雷电(我没试过雷电能不能玩，可能被检测出模拟器)，还是用别的

**Comment by Vacuumvoid** [comment]
那我先看看吧，今晚晚点再汇报情况 😊

**Comment by Vacuumvoid** [comment]
那片博客稍看了一下，但是对我这种小白来说根本不知从何下手😵
刚刚也下了雷电，跟现在的MuMu一样，开了几秒后就闪退了。现在唯一能稳定扛住美服更新的模拟器只有夜神了。我今晚会试一下在我root的那台手机上装Magisk试试，不过我觉得现在模拟器上能让美服达到60FPS除了MuMu以外没有多大希望了😭

**Comment by Vacuumvoid** [comment]
今晚一直在稿Magisk可是SafetyNet一直通不过，后来把Magisk卸了之后手机就重启不了了，后来重新flash了一遍后才可启动。。。看来美服真的不喜欢让人碰啊😓

**Comment by Vacuumvoid** [comment]
今天试了一天可是FGO就是和Magisk过不去，可能新的更新加了root/Magisk探测功能吧。除了Magisk以外有没有其他的方式？比如在模拟器上通过CE的Group Search来修改`set_targetFrameRate`的变量？

**Comment by hexstr** [comment]
刚从play store下载美服试了一下，用magisk没问题。

> 通过CE的Group Search来修改set_targetFrameRate的变量

这个不太好操作，你要保证打开游戏的瞬间修改完成，不然代码执行过后改了也没用

**Comment by Vacuumvoid** [comment]
请问一下您的Magisk是什么版本的？我试过19.3和20.4两个都在我的手机上装过，`MagiskHide`和`MagiskHide Props Config`也开启了，SafetyNet两个灯也是亮的，所有谷歌相关的程序（包括FGO）都加在`MagiskHide`的清单里，可是装完Magisk后每次开FGO就跳到Email。。。

**Comment by hexstr** [comment]
还要隐藏包名和关闭usb调试

**Comment by Vacuumvoid** [comment]
我明天再试试吧，再不行就有可能是手机的问题了

**Comment by salterz** [comment]
> 我明天再试试吧，再不行就有可能是手机的问题了

**Comment by salterz** [comment]
似乎今天bgo更新之后用模块就会闪退了。。

**Comment by hexstr** [comment]
> 似乎今天bgo更新之后用模块就会闪退了。。

#13

**Comment by Vacuumvoid** [comment]
我先暂时放弃了。。。以后多点时间会再来试试

**Comment by Axovur** [comment]
大神你好，我回来了
不知道为什么在旧手机上Magisk Hide就是不行，不过现在在新机子上一点问题都没有。
请问一下现在是不是把30调成60，如果是的话有没有机会可以推出一个120的模块？
或者是有没有教程教改加compile?

**Comment by Vacuumvoid** [comment]
大神你好，我回来了
不知道为什么在旧手机上Magisk Hide就是不行，不过现在在新机子上一点问题都没有。
请问一下现在是不是把30调成60，如果是的话有没有机会可以推出一个120的模块？
或者是有没有教程教改加compile?

**Comment by hexstr** [comment]
正准备跑路咕咕咕的...我忘了美服有没有自定义FPS的功能，等下看看

**Comment by hexstr** [comment]
现在可以自定义fps了

**Comment by Vacuumvoid** [comment]
好嘞，多谢大神！
