### ISSUE TITLE
国服更新1.66后好像会闪退

### ISSUE THREAD

**Issue by ashesofalar** [nishuoshenme/fgoUnlockFPS#13]
使用的是面具模块，magisk20.1，riru core19.7

**Comment by hexstr** [comment]
国服直接改`com.bilibili.fatego.v2.playerprefs.xml`不就好了，不需要模块

**Comment by ashesofalar** [comment]
好的，因为一直用的模块所以没注意可以直接改，感谢

**Comment by salterz** [comment]
注意到了，感谢
