### ISSUE TITLE
BGO模块更新后用不了了

### ISSUE THREAD

**Issue by zjss0415** [nishuoshenme/fgoUnlockFPS#14]
错误日志：
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/umi/umi:10/QKQ1.191117.002/V11.0.15.0.QJBCNXM:user/release-keys'
Revision: '0'
ABI: 'arm'
Timestamp: 2020-04-13 18:25:54+0800
pid: 20787, tid: 20805, name: bilibili.fateg  >>> com.bilibili.fatego <<<
uid: 10356
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x1e8
Cause: null pointer dereference
    r0  00000000  r1  e7c0f926  r2  bb7e8090  r3  00000000
    r4  b9b79a10  r5  00000000  r6  b9ac3234  r7  bb7e81e8
    r8  bb7e8174  r9  b9af979c  r10 bb7e8118  r11 bb7e805c
    ip  e50e7d20  sp  bb7e8020  lr  e7bb1107  pc  b9ac3254

backtrace:
      #00 pc 00135254  /data/app/com.bilibili.fatego-Gm1E0LisF7I_Wap-qcLP3w==/lib/arm/libmono.so
      #01 pc 0002e105  /system/lib/libriru_bgofpsunlocker.so (BuildId: 27c3a8eafbc85e148b0f2e5be2c8519e61151fd0)
      #02 pc 0002e531  /system/lib/libriru_bgofpsunlocker.so (BuildId: 27c3a8eafbc85e148b0f2e5be2c8519e61151fd0)
      #03 pc 000acced  /apex/com.an

**Comment by hexstr** [comment]
#13
