### ISSUE TITLE
bgo 4月13日更新 1.66.0版本magisk模块闪退

### ISSUE THREAD

**Issue by rico-chen** [nishuoshenme/fgoUnlockFPS#15]
官服

**Comment by ToyamaNao4477** [comment]
同1.66.0版本闪退

**Comment by hexstr** [comment]
#13

**Comment by rico-chen** [comment]
> #13

可惜加代码只能60左右浮动，用你的模块是可以稳定90的

**Comment by hexstr** [comment]
> > #13
> 
> 可惜加代码只能60左右浮动，用你的模块是可以稳定90的

那我等下更新

**Comment by rico-chen** [comment]
> > > #13
> > 
> > 
> > 可惜加代码只能60左右浮动，用你的模块是可以稳定90的
> 
> 那我等下更新

就是不知道为啥自定义里写90还是60，要写120才能90

**Comment by hexstr** [comment]
搞定，[bgo](https://github.com/nishuoshenme/FGOFPSUnlocker/releases/tag/bgo)  
我不知道能不能到90fps，你先测试一下吧

**Comment by rico-chen** [comment]
> 搞定，[bgo](https://github.com/nishuoshenme/FGOFPSUnlocker/releases/tag/bgo)
> 我不知道能不能到90fps，你先测试一下吧

确实可以90了，不过我暂时发现了几个bug，1.主界面御主头像到每周任务那一块整块不见了 2.卡池的抽卡按钮不见了 3.灵基一览点进去没有东西

**Comment by hexstr** [comment]
还有这事.jpg  
那还是先别用了

**Comment by rico-chen** [comment]
枯了

**Comment by hexstr** [comment]
更新了

**Comment by rico-chen** [comment]
自定义帧率和之前一样吗？好像不能上90

**Comment by hexstr** [comment]
一样，你把`com.bilibili.fatego.v2.playerprefs.xml`改回来再试试

**Comment by rico-chen** [comment]
我直接重装之后可以90了，大佬牛批
