### ISSUE TITLE
国服模块使用一段时间后掉回30帧

### ISSUE THREAD

**Issue by zjss0415** [nishuoshenme/fgoUnlockFPS#17]
大佬，我这边出现两例国服模块使用一段时间后掉回30帧的情况。重装模块、重装游戏、全删了从零开始安装游戏和模块都试过了，unlocker文件也正常，开始有60/90帧，但是现在只有30帧。

**Comment by hexstr** [comment]
自己看日志  
~~~
logcat -s ethereal:V
~~~

**Comment by zjss0415** [comment]
是在终端模拟器中输入然后打开BGO吗，输入之后显示
sdcard logcat -S ethereal:V
——beginning of system 
——beginning of main
read: unexpected EOF !

**Comment by hexstr** [comment]
你这什么都没有，模块都没工作

**Comment by zjss0415** [comment]
不对啊…我用自己的能60帧的国服输这个都没东西出来…，😥

**Comment by hexstr** [comment]
之前的没有，昨天`1.66.0`更新的会带上一堆`debug信息`比如`read cfg: 60`

**Comment by hexstr** [comment]
`-s`是小写

**Comment by zjss0415** [comment]
从MT的终端模拟器换成Ansole才出东西...
:/ $ su
:/ # logcat -s ethereal:V
--------- beginning of system
--------- beginning of main
04-17 18:24:54.669  5536  5548 D ethereal: ***** new thread: [5548] *****
04-17 18:25:04.669  5536  5548 D ethereal: ***** begin *****04-17 18:25:04.680  5536  5548 D ethereal: start_addr D2350000
04-17 18:25:04.698  5536  5548 D ethereal: mono_get_root_domain: 84 address: 16B79C
04-17 18:25:04.698  5536  5548 D ethereal: mono_thread_attach: 94 address: 2361A0
04-17 18:25:04.698  5536  5548 D ethereal: mono_object_new: 142 address: 1F5D60
04-17 18:25:04.698  5536  5548 D ethereal: mono_class_from_name: 174 address: 14D83C
04-17 18:25:04.699  5536  5548 D ethereal: mono_runtime_object_init: 694 address: 1EBA10
04-17 18:25:04.699  5536  5548 D ethereal: dlopen failed: dlopen failed: library "/system/lib/libmono.so" not found
04-17 18:25:04.700  5536  5548 D ethereal: ***** finish *****

**Comment by hexstr** [comment]
看样子是`libmono.so`没有复制到`/system/lib/`里，什么原因我也不清楚
