### ISSUE TITLE
Support variable frame rate

### ISSUE THREAD

**Issue by AioiLight** [nishuoshenme/fgoUnlockFPS#20]
Is it possible to unlock the frame rate for things like running `targetFrameRate` during the game (e.g. jp.co.cygames.umamusume)?

It may be possible to change the frame rate periodically, or hook the property changing

**Comment by hexstr** [comment]
Okay, i'll add a timer to handle this.

**Comment by AioiLight** [comment]
![image](https://user-images.githubusercontent.com/13918537/152178348-70eb3d7c-093a-4752-bc2d-86e51a9a43d9.png)

Latest release works perfectly. Thanks!
