### ISSUE TITLE
FGO国服失效

### ISSUE THREAD

**Issue by naraluwan1** [nishuoshenme/fgoUnlockFPS#21]
小米手机安卓11升级到安卓12，升级前正常，升级后使用1.5版本模块和zygisk，targetlist配置无误，日志如下，麻烦排查下问题，谢谢！
:/ $ su
:/ # logcat -s UnityFPSUnlocker:V
--------- beginning of main
03-28 13:32:12.090  3325  3326 D UnityFPSUnlocker: [UnityFPSUnlocker]initializing...
03-28 13:32:26.109  6692  6702 D UnityFPSUnlocker: ***** new thread *****
03-28 13:32:26.109  6692  6702 D UnityFPSUnlocker: delay: 10 | framerate: 120
03-28 13:32:35.622  6692  6702 D UnityFPSUnlocker: ***** begin *****
03-28 13:32:35.624  6692  6702 D UnityFPSUnlocker: il2cpp_resolve_icall not found, trying plan B...69
03-28 13:32:35.624  6692  6702 D UnityFPSUnlocker: Failed, not support this game.
03-28 13:37:47.124 15194 15202 D UnityFPSUnlocker: ***** new thread *****
03-28 13:37:47.124 15194 15202 D UnityFPSUnlocker: delay: 10 | framerate: 120
03-28 13:37:57.125 15194 15202 D UnityFPSUnlocker: ***** begin *****
03-28 13:37:57.127 15194 15202 D UnityFPSUnlocker: il2cpp_resolve_icall not found, trying plan B...69
03-28 13:37:57.127 15194 15202 D UnityFPSUnlocker: Failed, not support this game.
p03-28 13:45:08.612 17192 17203 D UnityFPSUnlocker: ***** new thread *****
03-28 13:45:08.612 17192 17203 D UnityFPSUnlocker: delay: 10 | framerate: 120
03-28 13:45:18.613 17192 17203 D UnityFPSUnlocker: ***** begin *****
03-28 13:45:18.614 17192 17203 D UnityFPSUnlocker: il2cpp_resolve_icall not found, trying plan B...69
03-28 13:45:18.614 17192 17203 D UnityFPSUnlocker: Failed, not support this game.

**Comment by hexstr** [comment]
换了个依赖库，你再试试？

**Comment by naraluwan1** [comment]
> 换了个依赖库，你再试试？

重新安装了1.6，可以正常运行。感谢大佬！
