### ISSUE TITLE
After 1.6 update the module will trigger appguard or any other root detecting/anticheat plugin

### ISSUE THREAD

**Issue by MaxPSN** [nishuoshenme/fgoUnlockFPS#22]
The 1.6 "works" on unlocking fps on more apps such as Princess Connect ReDive but it has a huge downside. The anticheat doesn't like it.

After the framerate unlocking progress started the game will be crashed or it will trigger the "security policy violation has been detected" dialog and then the app will shut down. 
This happens on every single app with anticheat implicated (including Princess Connect ReDive), and regardless the unlocking is working or not. Making it unusable. 
But rolling back to 1.5, everything will be fine again.

I have tested in on several different machines on Android Pie, 11 and 12. All of them are getting the same result.

Here's what I have used to hide root from apps
Magisk 24.3 (24300) 
Shamiko 0.5.0 (110)
Universal SafetyNet Fix 2.2.1

I suggest put the zygisk module 1.5 back for people who isn't using it for FGO until the issue is resolved.

**Comment by hexstr** [comment]
It's wired, in my opinion, the 1.5 should be detected too. Because after 1.5, I modify the memory to prevent from the game re-lock fps, and it triggers the anti-cheat.

**Comment by MaxPSN** [comment]
Ah right, sorry. It seems to be my bad. 
It happened to be all the games that have problem did not work on 1.5. So they trigger the anticheat on 1.6 when the framerate unlock is working.
I add all the games in the TargetList. But if the module isn't working, I launch games through [GLTools](https://gltools.app/) so I didn't notice about that until now. Guess the solution is I remove them from the list.

Anyway the link of the Princess Connect game and some other examples I tested. 
[プリンセスコネクト！Re:Dive](https://apkpure.com/%E3%83%97%E3%83%AA%E3%83%B3%E3%82%BB%E3%82%B9%E3%82%B3%E3%83%8D%E3%82%AF%E3%83%88%EF%BC%81re-dive/jp.co.cygames.princessconnectredive) game crash
[サモンズボード](https://apkpure.com/%E3%82%B5%E3%83%A2%E3%83%B3%E3%82%BA%E3%83%9C%E3%83%BC%E3%83%89/jp.gungho.bm) game crash
[シン・クロニクル](https://apkpure.com/%E3%82%B7%E3%83%B3%E3%83%BB%E3%82%AF%E3%83%AD%E3%83%8B%E3%82%AF%E3%83%AB/com.sega.sinch) security policy dialog and game shut down (GLTools doesn't work on this one but the 1.6 module successfully unlocked the fps)

The way GLTools unlock framerate doesn't trigger anticheat but it has a few seconds delay. It does re-unlock fps during gameplay. (Princess Connect ReDive re-lock fps on every scene transition)

**Comment by hexstr** [comment]
To deal with the anti-cheat is not a good idea, so I add an option to enable|disable modify opcode, it will work for those games.

**Comment by MaxPSN** [comment]
Thanks. Was going to live without it. It's working on those games now.
