### ISSUE TITLE
是否可以在TargetList.json中设置两组不同的列表

### ISSUE THREAD

**Issue by LaplaceTor** [nishuoshenme/fgoUnlockFPS#25]
以使得能够在 赛马娘 之类的游戏中获得帧数解锁的同时，不会在 公主链接 等游戏中因anticheat组件而闪退

Is it possible to set 2 different list in targetlist.json, to pass anticheat in games such as Princess Connect, and get real fps unlock in other games such as Umamusume at the same time

**Comment by hexstr** [comment]
你说的不同的列表是指`modify_opcode`选项吗？

**Comment by LaplaceTor** [comment]
> 你说的不同的列表是指`modify_opcode`选项吗？

是的，

**Comment by hexstr** [comment]
搞定，试试[`1.8`](https://github.com/hexstr/UnityFPSUnlocker/releases/download/UnityFPSUnlocker/zygisk_module_1.8.zip)  
[`TargetList.json`](https://github.com/hexstr/UnityFPSUnlocker/releases/download/UnityFPSUnlocker/TargetList.json)格式变更了，需要重新下载设置

**Comment by LaplaceTor** [comment]
> 搞定，试试[`1.8`](https://github.com/hexstr/UnityFPSUnlocker/releases/download/UnityFPSUnlocker/zygisk_module_1.8.zip)  
> [`TargetList.json`](https://github.com/hexstr/UnityFPSUnlocker/releases/download/UnityFPSUnlocker/TargetList.json)格式变更了，需要重新下载设置

可以了
