### ISSUE TITLE
請問

### ISSUE THREAD

**Issue by zhgallon** [nishuoshenme/fgoUnlockFPS#27]
電腦的模擬器是否無法使用？有安裝面具了。

**Comment by hexstr** [comment]
模拟器没必要装吧，应该自带120FPS

**Comment by hexstr** [comment]
你可以先检查一下游戏是什么架构，在`/data/app/{package-name}/lib`里有文件夹，一般是`arm64`

**Comment by zhgallon** [comment]
感謝回覆。包裡是arm64沒錯。因為遊戲有強制鎖30幀。模擬器也打不開高幀數。

**Comment by zhgallon** [comment]
喔抱歉回家查看模擬器裡的包是ARM不是ARM64，跟手機的不一樣。

**Comment by hexstr** [comment]
安装[这个](https://f-droid.org/packages/com.dp.logcatapp/)，过滤`UnityFPSUnlocker`，如果没有就是不支持。

**Comment by zhgallon** [comment]
看起來是不能，謝謝大佬了。

**Comment by hexstr** [comment]
可以试试[这个](https://github.com/hexstr/UnityFPSUnlocker/releases/tag/For-x86-Only)
