### ISSUE TITLE
有考虑适配Windows Subsystem for Android吗

### ISSUE THREAD

**Issue by Ryuz1nc** [nishuoshenme/fgoUnlockFPS#28]
在WSA装magisk后刷模块显示存在兼容性问题
![image](https://user-images.githubusercontent.com/69114658/183225439-b325a977-ee65-4c1f-bbe3-861e8f99bc43.png)

**Comment by hexstr** [comment]
我这边没用WSA所以暂时不会适配

**Comment by hexstr** [comment]
大概知道怎么回事了，下午更新

**Comment by hexstr** [comment]
可以试试[这个](https://github.com/hexstr/UnityFPSUnlocker/releases/tag/For-x86-Only)

**Comment by SekiBetu** [comment]
> 可以试试[这个](https://github.com/hexstr/UnityFPSUnlocker/releases/tag/For-x86-Only)

请问这个release是专用版吗，还是以前版本的更新版，如果是专用版，其实可以分出一个branch存代码，这样不会搞混

**Comment by hexstr** [comment]
@SekiBetu
专用版，没打算更新，没有代码

而且还不知道能不能用
