### ISSUE TITLE
zygist_module_1_8 无法120帧

### ISSUE THREAD

**Issue by kuruoky** [nishuoshenme/fgoUnlockFPS#31]
{
    "framerate": 120,
    "delay": 10,
    "normal_list": [
        "com.nexon.bluearchive",
        "com.sunborn.girlsfrontline.cn",
        "com.miHoYo.Yuanshen"
    ],
    "mod_list": [
        "com.aniplex.fategrandorder",
        "com.bilibili.fatego"
    ]
}

TargetList 设置如上，fgo运行设备显示帧率始终保持60（平板是120HZ的三星S7+）

**Comment by kuruoky** [comment]
日志显示配置正常 set_frame=120
![image](https://user-images.githubusercontent.com/29598878/188305970-32afd9ec-6614-4bce-9670-2804ff7c6766.png)

**Comment by kuruoky** [comment]
游戏内刷新率显示始终为60
![image](https://user-images.githubusercontent.com/29598878/188306048-a5341841-cb04-4b44-82b4-5ed965d8ccc0.png)

**Comment by hexstr** [comment]
不开插件也是60吗？

**Comment by kuruoky** [comment]
> 不开插件也是60吗？
对的，不开插件也是显示60帧

**Comment by kuruoky** [comment]
![image](https://user-images.githubusercontent.com/29598878/188306471-12e278d8-3722-4cda-b115-17ccbce6d1e5.png)
![image](https://user-images.githubusercontent.com/29598878/188306488-5b84c20c-93ac-4f29-ac0f-928a153cb514.png)
![image](https://user-images.githubusercontent.com/29598878/188306607-96b1134e-ec69-474e-b143-9a5b5600eff2.png)
重启后，插件disable，游戏内刷新率保持60帧，logcat显示无unlocker日志

**Comment by hexstr** [comment]
差点被带偏了，你这是开发者选项中的“显示当前的显示屏刷新频率”吧，看fps用别的软件。还有这是app的屏幕刷新率被锁定到了60，你要看看怎么解锁。
比如我大氢可以用“settings put global oneplus_screen_refresh_rate 0”设置全局120，三星没用过不知道。

**Comment by hexstr** [comment]
差点被带偏了，你这是开发者选项中的“显示当前的显示屏刷新频率”吧，看fps用别的软件。还有这是app的屏幕刷新率被锁定到了60，你要看看怎么解锁。
比如我大氢可以用“settings put global oneplus_screen_refresh_rate 0”设置全局120，三星没用过不知道。

**Comment by kuruoky** [comment]
> 差点被带偏了，你这是开发者选项中的“显示当前的显示屏刷新频率”吧，看fps用别的软件。还有这是app的屏幕刷新率被锁定到了60，你要看看怎么解锁。 比如我大氢可以用“settings put global oneplus_screen_refresh_rate 0”设置全局120，三星没用过不知道。

OK明白了谢谢
