### ISSUE TITLE
2.0配置文件格式问题

### ISSUE THREAD

**Issue by SekiBetu** [nishuoshenme/fgoUnlockFPS#33]
mod_list
normal_list
这两个选项在新版取消了吗，默认global就能用？
custom不填的话他是自动识别unity游戏包名的嘛

**Comment by hexstr** [comment]
`custom`只是用来单独设置的，不填的话默认用`global`的参数。
我说的不填是`"包名":{}`括号里面不填，不是把`custom`空着，看看新的配置文件就懂了。

**Comment by SekiBetu** [comment]
> `custom`只是用来单独设置的，不填的话默认用`global`的参数。 我说的不填是`"包名":{}`括号里面不填，不是把`custom`空着，看看新的配置文件就懂了。

懂了，我被custom字段迷惑了，就给删了以为现在已经智能识别unity引擎的APP了，重启之后发现没解锁帧率，再给加回去了

**Comment by hexstr** [comment]
@SekiBetu 识别还不简单，判断有没有加载`libunity.so`就行，~~但是这样插件会在每个app中加载一次，不太喜欢这样~~

哦现在也是在每个app中加载了一次，那说不定可以实现一下

**Comment by SekiBetu** [comment]
> @SekiBetu 识别还不简单，判断有没有加载`libunity.so`就行，~但是这样插件会在每个app中加载一次，不太喜欢这样~
> 
> 哦现在也是在每个app中加载了一次，那说不定可以实现一下

如果custom中缺字段，比如delay不写，只写了fps，他delay是会用global的吗

**Comment by hexstr** [comment]
@SekiBetu 是的

**Comment by hexstr** [comment]
搞定，现在可以自动识别是不是`unity`游戏了
