### ISSUE TITLE
3.0自动检测问题

### ISSUE THREAD

**Issue by SekiBetu** [nishuoshenme/fgoUnlockFPS#34]
所有APP都判断不好吧，有性能问题吧？
再加个设置，只在特定APP加载？
只有为false才加载custom里的设置这样

```json
{
    "global": {
        "autodetect": true/false
    }
}
```

**Comment by hexstr** [comment]
就检测文件夹是否存在能有什么性能损耗，不加，C语言性能还是可靠的

**Comment by SekiBetu** [comment]
> 就检测文件夹是否存在能有什么性能损耗，不加，C语言性能还是可靠的

`3.0通过判断是否存在/sdcard/Android/data/{package_name}/files/il2cpp来自动加载。`

这里指的是所有的APP的路径吗，即使custom里指定了包名，也会检测别的吗

**Comment by SekiBetu** [comment]
```json
{
    "global": {
        "delay": 10,
        "mod_opcode": false,
        "fps": 60
    },
    "custom": {
        "com.bilibili.fatego": {}
    }
}
```

比如我这样的配置，那么除了BGO以外的APP是不是也会被应用上这个解锁FPS功能

**Comment by hexstr** [comment]
@SekiBetu 对，你不是unity游戏也不会有这个文件夹啊
