### ISSUE TITLE
X86模擬器的配置文件

### ISSUE THREAD

**Issue by zhgallon** [nishuoshenme/fgoUnlockFPS#35]
請問大佬模擬器設備的模塊能做到像是其他模塊的自定義高刷配置嗎？剛好換了新的屏幕有高刷。謝謝。

**Comment by hexstr** [comment]
@zhgallon 可以是可以，就是要实现这个功能每次启动都要读一遍配置文件，等我有时间加上吧

**Comment by Zhen-Bo** [comment]
gltools 在模擬器好像只有解析度能用, 解鎖 fps 無法正常生效 (官方網載的X86版本)
不過我剛剛看到, 好像雷電 9 就是 120FPS 了? (設定開啟高FPS, 上限120)
還是說因為我有個 120fps 設定的 TargetList.json 跟 TargetListEmulator.json 共存的原因?
![120](https://user-images.githubusercontent.com/30999421/195125618-fb8ca6f1-6b67-4c0b-a1db-608b54fcb5bb.png)

**Comment by hexstr** [comment]
@Zhen-Bo 说不定就是模拟器自带啰

**Comment by Zhen-Bo** [comment]
> @Zhen-Bo 说不定就是模拟器自带啰

沒有, 一開始沒注意到有分 X86 版本用的是手機版本的, 確實會鎖 30FPS
改成 X86 版本就變成 120 了

**Comment by hexstr** [comment]
@Zhen-Bo X86的模块设置的是60FPS，那这里只是显示为120了

**Comment by Zhen-Bo** [comment]
> @Zhen-Bo X86的模块设置的是60FPS，那这里只是显示为120了

原來, 這點差異沒放在一起比較我真的感覺不出來😅

**Comment by hexstr** [comment]
@zhgallon @Zhen-Bo 单独写了份120FPS的，先用这个吧

**Comment by hexstr** [comment]
@Zhen-Bo 捏麻麻地怎么恁湾友也开始流汗黄豆了

**Comment by Zhen-Bo** [comment]
> @Zhen-Bo 捏麻麻地怎么恁湾友也开始流汗黄豆了

![image](https://user-images.githubusercontent.com/30999421/195376998-872133e2-e8ed-4fed-b185-e7c4be48afdc.png)
不是微軟自帶的輸入法就可以快速叫出emoji的表單了嗎
還蠻常用的 LOL

**Comment by zhgallon** [comment]
謝謝作者抽空新增。可以正常運作。感恩！

**Comment by Zhen-Bo** [comment]
正常運作+1
PS:如果不把60fps 跟 120fps放一起比較還真的沒法察覺LOL

**Comment by hexstr** [comment]
@Zhen-Bo ( ﾟ∀。)看来是我想多了，抱歉抱歉

**Comment by Zhen-Bo** [comment]
> @Zhen-Bo ( ﾟ∀。)看来是我想多了，抱歉抱歉

這個emoji是有啥特殊的含意嗎🤔

**Comment by hexstr** [comment]
@Zhen-Bo 简中局域网的烂梗

**Comment by Zhen-Bo** [comment]
原來😂

hexstr ***@***.***> 於 2022年10月13日 週四 下午12:09 寫道：

**Comment by hexstr** [comment]
https://github.com/hexstr/UnityFPSUnlocker/releases/tag/3.1
