### ISSUE TITLE
模擬器高FPS設定問題

### ISSUE THREAD

**Issue by Zhen-Bo** [nishuoshenme/fgoUnlockFPS#36]
如題
想請問下有沒有辦法拉高模擬器的FPS參數
想要在模擬器上玩到120甚至是144FPS的畫面
順便配上gltools拉高解析度
不過我看release那邊固定鎖60FPS
想問下能不能開放FPS上限

**Comment by Zhen-Bo** [comment]
抱歉沒仔細看open的那個issue
OTz

**Comment by hexstr** [comment]
#35
有时间再弄，不过你既然用gltools那直接改不就好了
