### ISSUE TITLE
你好，关于3.3版本问题

### ISSUE THREAD

**Issue by MuYuehe** [nishuoshenme/fgoUnlockFPS#39]
面具我用的25.2，刷模块显示![S30217-01073973.png](https://user-images.githubusercontent.com/93329319/219437847-bdbfc4cb-e493-4b36-8541-01b53593017b.png)

重启也不行，另外问一下3.3的配置文件在哪？

手机架构arm64-v8a

**Comment by hexstr** [comment]
解压失败估计是文件损坏，重新下载就行
配置文件在3.1里下载

**Comment by MuYuehe** [comment]
大大，我觉得3.3还是有问题，我重新下载重启也不行，试了其他版本能刷上

**Comment by hexstr** [comment]
那就先用其他版本，我有时间检查一下3.3

**Comment by hexstr** [comment]
确实有问题，我已经重新打包了
看来不能用Windows自带的压缩

**Comment by MuYuehe** [comment]
谢谢，可以刷上了
另外问一下，mod_opcode为true的时候是修改内存，为false的时候是相当于1.8配置中的normal_list是吗

**Comment by hexstr** [comment]
是的

> 谢谢，可以刷上了 另外问一下，mod_opcode为true的时候是修改内存，为false的时候是相当于1.8配置中的normal_list是吗
