### ISSUE TITLE
可否支持下渠道客户端

### ISSUE THREAD

**Issue by a546109781** [nishuoshenme/fgoUnlockFPS#4]
比如享游客户端，包名是com.bilibili.fatego.sharejoy。。有两个号，因为手机现在没法双开，只能用别的客户端同时玩了

**Comment by nishuoshenme** [comment]
4c844aa2de0a5e76b04a65edbb4d30b7f767412b
在releases下载更新后的文件试试

**Comment by a546109781** [comment]
可以了，谢谢！
