### ISSUE TITLE
请问会考虑支持lspatch吗

### ISSUE THREAD

**Issue by JeanneAlt** [nishuoshenme/fgoUnlockFPS#41]
原理上可行吗

**Comment by hexstr** [comment]
这个简单，我编译成libmain.so就能拿来替换原来的libmain.so了，不过有些游戏对so文件有校验，可能会直接闪退

**Comment by JeanneAlt** [comment]
原来是这样，我记得之前就有这么改bgo高帧的，是不是有校验才不用这种方法了

**Comment by hexstr** [comment]
试试3.6.2

**Comment by JeanneAlt** [comment]
> 试试3.6.2
bgo修补后直接闪退，查了下好像是有加固的原因？不知道别的游戏能用不，手机上没有

**Comment by hexstr** [comment]
绷，看来要加一条说明不支持中国版unity
![Snipaste_2023-05-24_13-00-38](https://github.com/hexstr/UnityFPSUnlocker/assets/28940831/7ab08532-8821-4a0b-8ac9-7713e9298486)
