### ISSUE TITLE
It is set to 120fps, but it is not reflected.

### ISSUE THREAD

**Issue by reindex-ot** [nishuoshenme/fgoUnlockFPS#45]
I am sure that the description is correct, but does it mean that it is not recognized unless it is UTF-8?

**Comment by hexstr** [comment]
It's a bug, please use 3.4

**Comment by reindex-ot** [comment]
There was still a symptom that 120 fps was not reflected in 緋染天空(Heaven Burns Red)...(;_;)
https://m-apps.qoo-app.com/en-US/app/10878

**Comment by hexstr** [comment]
@reindex-ot I need more details

**Comment by reindex-ot** [comment]
Logcat.
Max framerate 77.
`04-14 00:33:46.701 14777 14803 D UnityFPSUnlocker: ***** begin *****`
`04-14 00:33:46.701 14777 14803 D UnityFPSUnlocker: set_targetFrameRate: 77`
`04-14 00:33:46.701 14777 14803 D UnityFPSUnlocker: ***** finished *****`
`04-14 00:33:47.814 15181 15214 D UnityFPSUnlocker: ***** begin *****`
`04-14 00:33:47.814 15181 15214 D UnityFPSUnlocker: Failed, not support this game.`
`04-14 00:34:10.369 23384 23395 D UnityFPSUnlocker: [UnityFPSUnlocker][arm64] Starting...`
`04-14 00:34:10.369 23384 23395 D UnityFPSUnlocker: delay: 7 | framerate: 77 | modify_opcode: 0`
`04-14 00:34:17.369 23384 23395 D UnityFPSUnlocker: ***** begin *****`
`04-14 00:34:17.369 23384 23395 D UnityFPSUnlocker: set_targetFrameRate: 77`
`04-14 00:34:17.370 23384 23395 D UnityFPSUnlocker: ***** finished *****`

Unity
[https://forpro.unity3d.jp/case_study/wright-flyer-studios/](https://forpro.unity3d.jp/case_study/wright-flyer-studios/)

**Comment by hexstr** [comment]
update `TargetList.json`

**Comment by reindex-ot** [comment]
![IMG_20230415_140956](https://user-images.githubusercontent.com/32851879/232184373-9372ccc9-ef1f-412a-89c0-8f7ea368b3d7.jpg)
thx hexstr!
君の事マジ好き。
