### ISSUE TITLE
请问新版本的json还是老位置吗

### ISSUE THREAD

**Issue by KuonjiAsukai** [nishuoshenme/fgoUnlockFPS#46]
我以前一直用着老版本的unlocker，json也是老版的，正常使用没问题。今天手机双清后发现有更新，但是并不能保持120帧，挺迷惑的，不知道问题出现在哪

**Comment by hexstr** [comment]
`/data/local/tmp/TargetList.json`
不知道你用的旧版是哪个，可能配置文件的格式有变化

**Comment by hexstr** [comment]
~~哦草，#43合并的pr有问题，等我改一下`TargetList.json`~~
改完了，重新下载`TargetList.json`

**Comment by KuonjiAsukai** [comment]
好的爱你😘

**Comment by KuonjiAsukai** [comment]
![Screenshot_2023-04-14-21-58-58-431_com omarea vtools](https://user-images.githubusercontent.com/90266622/232066860-1e07c02e-d161-4bc0-8446-97a2ed1cd038.jpg)
![Screenshot_2023-04-14-21-58-38-031_com omarea vtools](https://user-images.githubusercontent.com/90266622/232066870-41ddff11-30d9-4ae2-a42a-29b47d3ac5a5.jpg)
大佬我更新3.5的json后发现帧率还是不正常，主界面90浮动，自从进副本之后一直锁死30，看了一下监控好像gpu在偷懒。
我找回1.6版本的模块用反而能稳定，gpu也有动起来。
再者就想问下模块运行日志怎么调出来。。😥
