### ISSUE TITLE
[bug]大概是系统兼容性问题

### ISSUE THREAD

**Issue by kcn3388** [nishuoshenme/fgoUnlockFPS#48]
设备机型：魅族20 Pro
系统：Android13， Flyme10
故障：解锁后最高只有60帧，无论文件内是60还是120
log：正常调用log，显示修改完成但实际上没生效，log无报错

**Comment by hexstr** [comment]
看看这里
https://github.com/hexstr/UnityFPSUnlocker/issues/31#issuecomment-1236297286

**Comment by kcn3388** [comment]
@hexstr 已解决，开发者选项内开启强制90hz即可
120hz的屏选项是90hz的，严重怀疑是搬的17的代码
