### ISSUE TITLE
请问日服如何在模拟器下实现60帧的功能？

### ISSUE THREAD

**Issue by 523883312** [nishuoshenme/fgoUnlockFPS#5]
手机的电量长时间实在是不太够用，而且一直手持也不太方便，想用模拟器方便一些，但模拟器没有办法安装magisk来屏蔽日服的ROOT检测以及安装模块来实现60帧功能，请问能否像之前那样通过修改system文件强制模拟器60帧同时跳过ROOT检测？

**Comment by nishuoshenme** [comment]
直接改il2cpp.so文件即可

**Comment by 523883312** [comment]
> 直接改il2cpp.so文件即可，现在新版本暂时没有检测

额，请问这个文件的路径在哪？还有如何更改so文件里的哪条代码才能启用？抱歉我纯小白不太懂这些

**Comment by nishuoshenme** [comment]
> > 直接改il2cpp.so文件即可，现在新版本暂时没有检测
> 
> 额，请问这个文件的路径在哪？还有如何更改so文件里的哪条代码才能启用？抱歉我纯小白不太懂这些

我给个现成的好了，2.0.1的，更新之后要重新弄。[链接](https://caomsacid0-my.sharepoint.com/:f:/g/personal/aquar_caoms_ac_id/EvKZOE0a24pOr24_PYNu2K0BluWvXpnhnAYkye13X3h6ig?e=bGWZ3x)
下载后把文件重命名为libil2cpp.so并替换到模拟器中的/data/data/com.aniplex.fategrandorder/lib/中，替换之前把原来的文件重命名方便还原，建议模拟器中用re管理器操作

**Comment by 523883312** [comment]
> > > 直接改il2cpp.so文件即可，现在新版本暂时没有检测
> > 
> > 
> > 额，请问这个文件的路径在哪？还有如何更改因此文件里的哪条代码才能启用？抱歉我纯小白不太懂这些
> 
> 我给个现成的好了，2.0.1的，更新之后要重新弄。[链接](https://caomsacid0-my.sharepoint.com/:f:/g/personal/aquar_caoms_ac_id/EvKZOE0a24pOr24_PYNu2K0BluWvXpnhnAYkye13X3h6ig?e=bGWZ3x)
> 下载后把文件重命名为libil2cpp.so并替换到模拟器中的/data/data/com.aniplex.fategrandorder/lib/中，替换之前把原来的文件重命名方便还原，建议模拟器中用重管理器操作

好的，谢谢dalao
