### ISSUE TITLE
想问一下3.5版本的targetlist怎么写才能让在指定游戏不应用修改

### ISSUE THREAD

**Issue by 923133980** [nishuoshenme/fgoUnlockFPS#51]
我玩的有个游戏。因为修改就会在登录检验的时候闪退，也有些游戏没打算解锁帧率。我看targetlist是默认解锁的。有什么办法指定在某些游戏不解锁帧率呢

**Comment by hexstr** [comment]
@923133980 我没写233
一般主动调用的话不会被检测到，修改内存只会在mod_opcode设置为true时才会执行，把这个单独设置mod_opcode为false试试？

**Comment by 923133980** [comment]
好的我试试行不行

**Comment by 923133980** [comment]
试了试好像还是会闪退。不知道dalao如果将来有空可不可以加个对指定游戏不修改的配置_(:з」∠)_

**Comment by hexstr** [comment]
@923133980 把magisk的排除列表打开，然后勾选这个游戏

**Comment by 923133980** [comment]
哦哦还有这个。不过想问一下大佬知不知道Shamiko这个。好像就是要把排除列表关掉才会隐藏root生效的。我平时用这个对银行隐藏root。就是常态关闭 magisk排除列表。如果想要用这个模块但是过某游戏不闪退就要打开排除列表。是不是有冲突。_(:з」∠)_
