### ISSUE TITLE
CarX Street does not reflect settings

### ISSUE THREAD

**Issue by monefiera** [nishuoshenme/fgoUnlockFPS#52]
I want to run CarX Street(com.carxtech.sr) at 120 fps, but it doesn't reflect it. logcat shows 77 fps, but the game only shows 30 fps.

![Screenshot_20230416-173836_CarX_Street](https://user-images.githubusercontent.com/83483662/232287453-22fcaffe-0629-47ef-b660-e67b301edf7e.png)
The second photo is before applying with Target_List and the third photo is after.
![image](https://user-images.githubusercontent.com/83483662/232287545-c2bb7591-1550-4810-ba7c-2c3949eabb57.png)
![image](https://user-images.githubusercontent.com/83483662/232287557-f7a88783-f16e-4d08-9933-38f2620eeb89.png)
I believe the json file description, encoding, and placement of directory are all correct.
![image](https://user-images.githubusercontent.com/83483662/232287718-401a93f4-97c0-4255-84ea-ac4fd29a3f5c.png)
![image](https://user-images.githubusercontent.com/83483662/232287729-e743de7a-aa92-4f0d-8059-b3a135a47d3e.png)

**Comment by hexstr** [comment]
Grant 777 permission and try again
`chmod 777 /data/local/tmp/TargetList.json`

**Comment by monefiera** [comment]
Umm…I have tried but it does not work.
Is it OK to enter the above command after entering su in termux?
![Screenshot_20230417-120415_CarX Street](https://user-images.githubusercontent.com/83483662/232368460-e92035be-2d7b-4057-b96e-6322cdab7147.png)

**Comment by hexstr** [comment]
@FieraYuzuki yeah, i use termux too

**Comment by hexstr** [comment]
input in termux
`su`
`stat /data/local/tmp/TargetList.json`
`ls -lhtrZ /data/local/tmp/TargetList.json`
and upload screenshot

**Comment by monefiera** [comment]
I applied the command and rebooted, no change.
Below is the terminal when the command was entered.
![Screenshot_20230417-130619_Termux](https://user-images.githubusercontent.com/83483662/232376056-6509a102-90d7-4c43-af3b-570b6c054126.png)

**Comment by monefiera** [comment]
By the way, for some reason "logcat -s UnityFPSUnlocker" stopped working 😭
![Screenshot_20230417-132917_Termux~2](https://user-images.githubusercontent.com/83483662/232378334-a29a8e59-6358-4925-83fe-62895e595932.png)

**Comment by hexstr** [comment]
> By the way, for some reason "logcat -s UnityFPSUnlocker" stopped working 😭 ![Screenshot_20230417-132917_Termux~2](https://user-images.githubusercontent.com/83483662/232378334-a29a8e59-6358-4925-83fe-62895e595932.png)

`su`

**Comment by hexstr** [comment]
maybe the problem is the parent directory
`ls -lhZ /data/local`
`chmod 777 /data/local/tmp`

**Comment by monefiera** [comment]
I tried all the commands presented here, changing the order of input, but there was no change in fps...

**Comment by hexstr** [comment]
sorry i have no idea why the plugin cannot read configuration file even if the permission is `rwx`

**Comment by monefiera** [comment]
OK, thank you for your efforts to resolve this issue.

**Comment by monefiera** [comment]
I forgot to mention the most important thing.
I am currently using Magisk Delta on my device. So is there any possible impact from this?

**Comment by hexstr** [comment]
maybe not.
and just try to read it in termux **without su**
`cat /data/local/tmp/TargetList.json`
if it output the file content, the problem is not due to permission, i'll update a new version to write error to log file.

**Comment by FieraYuzuki** [comment]
I tried this without su, but the termux said "No such file or directory".
Is this a permissions issue?
![Screenshot_20230419-140249_Termux](https://user-images.githubusercontent.com/83483662/232971893-c60c605d-ac0e-469c-955e-32eb822aa630.png)

**Comment by monefiera** [comment]
The file was output successfully.
![Screenshot_20230419-141142_Termux~2](https://user-images.githubusercontent.com/83483662/232972924-cd64b96d-a6ff-4508-87cd-6e21b222c9ea.png)

**Comment by hexstr** [comment]
update 3.6.1

**Comment by monefiera** [comment]
I took the log again with 3.6.1.
It seems to be repeatedly causing "LoadConfig error: Parse error".
![Screenshot_20230420-115139_Termux](https://user-images.githubusercontent.com/83483662/233246120-b5626b7d-f836-4161-8079-f9e9d6715396.png)

**Comment by hexstr** [comment]
download TargetList.json and edit, don't change encoding

**Comment by monefiera** [comment]
I was able to successfully unlock the FPS lock. Thank you very much！
However, the game itself is too heavy, or the FPS only increased by 3～4... I guess I will have to overclock the GPU now.
