### ISSUE TITLE
启用模块后会导致shamiko无法完全隐藏zygisk

### ISSUE THREAD

**Issue by TinyTitanPro** [nishuoshenme/fgoUnlockFPS#53]
在用Momo检测root状态时，发现有“找到 Zygisk”这一项，通过开关模块排查发现是启用UnityFPSUnlocker模块导致的，关闭后就能过Momo检测了。由于工作原因需要对手机上的一些应用尽可能彻底地隐藏root和面具，请问是否有改进手段可以改善这一状况。
![)5LLI 6A5 16BOC%UA417WB](https://user-images.githubusercontent.com/13111767/232497897-121dc21f-5be7-4822-8b03-b23218409647.jpg)

**Comment by hexstr** [comment]
暂时没有，我没有这种需求所以没有研究过
