### ISSUE TITLE
是否所有的Unity Game都有效呢

### ISSUE THREAD

**Issue by Jansdin** [nishuoshenme/fgoUnlockFPS#54]
首先 非常感谢您开发这个模块.
我是使用模拟器  雷电9运行游戏
在**FGO**跟**机器人大战DD**这两个游戏上都能使用  真的是很愉快的游戏体验
但是在**魂斗罗归来**就失效了  我曾尝试许多方法都无法让他达到60FPS
希望能在你这边获得解决的方法

再次感谢!

**Comment by hexstr** [comment]
只支持用il2cpp后端编译的unity游戏，你要先看看游戏安装包里面有没有`lib\libil2cpp.so`这个文件

**Comment by Jansdin** [comment]
原来如此  我看了一下没有
那请问有其他方法能用吗?

**Comment by hexstr** [comment]
无，适配mono后端都是4年前的事了，你去找找别的项目吧

**Comment by Jansdin** [comment]
好的  感谢您的解答
