### ISSUE TITLE
求救

### ISSUE THREAD

**Issue by w66936989** [nishuoshenme/fgoUnlockFPS#55]
![QQ浏览器截图20230502000928](https://user-images.githubusercontent.com/112257525/235499547-5ccab8a1-3242-4240-b31e-3f239ddc0fd4.png)
好久不见 忘了怎么回复 只找到这里  话说 没打汉化有玛修和达芬奇  打上后居然没有这是撒情况 好像FGO因为更新了打上就没有了 哭

**Comment by hexstr** [comment]
fgo弃坑了模块已经不维护了
