### ISSUE TITLE
請問3.6.2是默認90幀嗎

### ISSUE THREAD

**Issue by chak813** [nishuoshenme/fgoUnlockFPS#57]
請問3.6.2是默認90幀嗎?
我用的是lspatch，按說明方法添加了config之後還是只有90幀
大佬能否做一個默認120幀的模塊，萬分感謝

**Comment by hexstr** [comment]
@chak813 暂时不会单独做固定fps的模块，不过配置文件未生效我有时间会看看

**Comment by chak813** [comment]
> 

謝謝

**Comment by hexstr** [comment]
无法复现，配置文件可以正常生效

![Snipaste_2023-08-01_17-33-32](https://github.com/hexstr/UnityFPSUnlocker/assets/28940831/231875dc-9435-4e83-8030-602810290fa6)

**Comment by chak813** [comment]
> 无法复现，配置文件可以正常生效
> 
> ![Snipaste_2023-08-01_17-33-32](https://user-images.githubusercontent.com/28940831/257471929-231875dc-9435-4e83-8030-602810290fa6.png)

可能是我用lspatch和分身的關係吧，因為原版經lspatch打包就會閃退，一定要用分身
90幀也湊合著玩吧，總比30幀強
