### ISSUE TITLE
FGO周年版本减速问题

### ISSUE THREAD

**Issue by kcn3388** [nishuoshenme/fgoUnlockFPS#58]
rt，周年版本其他地方正常，但是打开筛选（从者，礼装都是这样）的时候窗口打开会减速，实际表现类似于60FPS的屏幕强行跑144FPS

订正：大部分弹出式窗口都会表现出减速

**Comment by hexstr** [comment]
https://github.com/hexstr/FGOAssetsModifyTool/issues/105#issuecomment-1614639910
