### ISSUE TITLE
请问大佬FGO国服进入战斗后高帧失效应该怎么应对

### ISSUE THREAD

**Issue by 749956309** [nishuoshenme/fgoUnlockFPS#59]
大佬，我使用的是3.6.2版本Lsposed框架下的Unlocker，在FGO国服七周年版本更新后，进入战斗前可以高帧运行，但只要进入战斗就会重新变回30帧，结束后仍然保持30帧，直至重启游戏，请问我应该怎么解决这个问题呢？

**Comment by hexstr** [comment]
需要提供日志

**Comment by 749956309** [comment]
[ 2023-08-05T12:19:24.615    10290: 28992: 28992 I/LSPosed-Bridge  ] Loading module io.github.hexstr.unityfpsunlocker from /data/app/~~NZZOcKrekHHkbA71YbkQ2w==/io.github.hexstr.unityfpsunlocker-rdYok3UWKnLsrnBpcWPZPQ==/base.apk
[ 2023-08-05T12:19:24.616    10290: 28992: 28992 I/LSPosed-Bridge  ]   Loading class io.github.hexstr.unityfpsunlocker.MyModule
[ 2023-08-05T12:19:24.646    10290: 28992: 28992 I/LSPosed-Bridge  ] Loaded app: com.bilibili.fatego
[ 2023-08-05T12:19:50.976    10290: 28992: 28992 I/LSPosed-Bridge  ] Loaded app: com.google.android.webview

**Comment by hexstr** [comment]
如何查看日志我写在了readme最后一行

还有就是要先开logcat再打开游戏，不然旧日志会被新的覆盖掉

**Comment by 749956309** [comment]
# sdcard logcat -s UnityFPSUnlocker
--------- beginning of main
08-05 13:02:37.346 15778 15778 D UnityFPSUnlocker: cmdline: com.bilibili.fatego
08-05 13:02:37.348 15778  1681 D UnityFPSUnlocker: [UnityFPSUnlocker][arm64] Starting...
08-05 13:02:37.348 15778  1681 D UnityFPSUnlocker: delay: 10 | framerate: 120 | modify_opcode: 0
08-05 13:02:47.348 15778  1681 D UnityFPSUnlocker: ***** begin *****
08-05 13:02:47.348 15778  1681 D UnityFPSUnlocker: set_targetFrameRate: 120
08-05 13:02:47.348 15778  1681 D UnityFPSUnlocker: ***** finished *****

**Comment by hexstr** [comment]
在配置文件中把`modify_opcode`这个0改成1就行

**Comment by 749956309** [comment]
太强了大佬，解决了，十分感谢! mua

**Comment by 749956309** [comment]
README 里都写好了，我才注意到，鉴定为：瞎子。对不起大佬打扰到你了
