### ISSUE TITLE
请问是如何确定修改的位置的呢?

### ISSUE THREAD

**Issue by coolucifer** [nishuoshenme/fgoUnlockFPS#6]
现在用的华为P30, 没有办法装magisk, 参照了您的方法修改了apk中对应的文件实现了日服的60帧. 但是如果版本更新了的话修改的位置是不变的吗? 是如何确定要修改哪里的呢?

**Comment by nishuoshenme** [comment]
用[il2cppdumper](https://github.com/Perfare/Il2CppDumper)，用法自己看介绍

**Comment by coolucifer** [comment]
> 用[il2cppdumper](https://github.com/Perfare/Il2CppDumper)，用法自己看介绍

好的, 非常感谢.
