### ISSUE TITLE
[FEATURE REQUEST] Change camera field of view

### ISSUE THREAD

**Issue by d3xMachina** [nishuoshenme/fgoUnlockFPS#62]
Would it be possible to implement a setting to change the camera FOV like [here](https://blog.palug.cn/3088.html) ? 

This project is the only one that worked for me to change some unity games who have a lot of protections against dumping il2cpp. I've wanted to implement that myself but I don't know how you can get the instances and hook their funtion with xdl.

**Comment by d3xMachina** [comment]
I've finally found how to do that using code from [IL2CppAPI ](https://github.com/AKNoryx28/Il2CppAPI) and incorporating it in this project. I will post a fork once I've finished the dev.

I also found a way to dump the il2cpp.so that work on emulator with Auto-IL2cppDumper.

**Comment by hexstr** [comment]
There are no plans to add other features.
And use [il2cpp_resolve_icall](https://github.com/hexstr/UnityFPSUnlocker/blob/a879636d05e484b17a3d5ba51c47a9096feeb877/UnityFPSUnlocker/fpslimiter.cc#L46) to find unity api address is enouth.

**Comment by d3xMachina** [comment]
Ok, no problem!
