### ISSUE TITLE
在安卓 14挂了好像，coloros14

### ISSUE THREAD

**Issue by xiaouex** [nishuoshenme/fgoUnlockFPS#63]
lsposed版和模块版都无效了，哥看看啥原因呗

**Comment by hexstr** [comment]
抓个日志看看是不是显示`Cannot open libart.so.`

**Comment by xiaouex** [comment]
https://www.123pan.com/s/xWMZVv-FlMl.html
日志如上

**Comment by xiaouex** [comment]
> 抓个日志看看是不是显示`Cannot open libart.so.`
日志如下
https://www.123pan.com/s/xWMZVv-FlMl.html

**Comment by hexstr** [comment]
根据日志来看模块已经正确运行了
