### ISSUE TITLE
sif2似乎无法被识别为unity程序

### ISSUE THREAD

**Issue by YumeMichi** [nishuoshenme/fgoUnlockFPS#64]
启动游戏的时候logcat没有任何提示，帧率也没有变化。
可以确定该游戏是unity程序，也能到files目录下找到il2cpp相关的文件。
游戏apk：https://apkpure.com/%E3%83%A9%E3%83%96%E3%83%A9%E3%82%A4%E3%83%96%EF%BC%81%E3%82%B9%E3%82%AF%E3%83%BC%E3%83%AB%E3%82%A2%E3%82%A4%E3%83%89%E3%83%AB%E3%83%95%E3%82%A7%E3%82%B9%E3%83%86%E3%82%A3%E3%83%90%E3%83%AB2%EF%BC%88%E3%82%B9%E3%82%AF%E3%83%95%E3%82%A7%E3%82%B92%EF%BC%89/com.bushiroad.lovelive.schoolidolfestival2

**Comment by YumeMichi** [comment]
其他unity游戏会有类似提示，但是sif2没有
```
01-02 02:35:55.408 18302 18319 D UnityFPSUnlocker: [UnityFPSUnlocker][arm64] Starting...
01-02 02:35:55.408 18302 18319 D UnityFPSUnlocker: 	delay: 5 | fps: 144 | mod_opcode: 1 | scale: 1.000000
01-02 02:36:00.408 18302 18319 D UnityFPSUnlocker: ***** begin *****
01-02 02:36:00.411 18302 18319 D UnityFPSUnlocker: Current resolution: 2880x1800 @144
01-02 02:36:00.411 18302 18319 D UnityFPSUnlocker: Set resolution: 2880 x 1800
01-02 02:36:00.411 18302 18319 D UnityFPSUnlocker: ***** finished *****
```

**Comment by hexstr** [comment]
配置一下包名试试

**Comment by YumeMichi** [comment]
看起来是加壳了，那没办法了。
