### ISSUE TITLE
你好，在ColorOS14中，使用该模块部分游戏会限制90fps

### ISSUE THREAD

**Issue by mikuxixi** [nishuoshenme/fgoUnlockFPS#65]
我的设备是 一加Ace2 Pro  型号：PJA110
游戏：dynamix 和 D4DJ 这两个音游使用该模块会限制90fps 并且游玩卡顿掉帧
把这两个加入custom 配置文件无效
包名：com.bushiroad.d4dj  (D4DJ) 
           com.c4cat.dynamix   (dynamix)

卸载该模块后恢复120fps

**Comment by hexstr** [comment]
发一下你的配置文件和和日志？

**Comment by mikuxixi** [comment]
[配置文件和日志.zip](https://github.com/hexstr/UnityFPSUnlocker/files/14156970/default.zip)
已经打包发送，这两个游戏是原生支持 120fps 的，但只有在开始游戏才会 120fps 选歌界面会回到 60fps

**Comment by hexstr** [comment]
配置文件有问题，还是先了解一下json语法
