### ISSUE TITLE
部分游戏会在files下创建config文件夹导致无法创建同名config文件

### ISSUE THREAD

**Issue by xiaouex** [nishuoshenme/fgoUnlockFPS#66]
如题，例如元气骑士前传会在files下创建一个名为config的文件夹，同名config文件无法创建，导致xp模块无法读取该游戏，建议把配置文件的名字改成别的，比如和magisk模块版一样的名字或者加上后缀，因为config.txt是可以创建的

**Comment by xiaouex** [comment]
附图
![Screenshot_2024-02-29-10-24-55-92_9e8df3d0c7c1f50](https://github.com/hexstr/UnityFPSUnlocker/assets/36121363/32b0e09a-ecf1-41ca-856e-10a94efa97a0)

**Comment by hexstr** [comment]
用最新版

**Comment by xiaouex** [comment]
> 用最新版

卧槽真快
