### ISSUE TITLE
赛马娘（日服)点击错位

### ISSUE THREAD

**Issue by McQck** [nishuoshenme/fgoUnlockFPS#67]
可能由于是竖屏游戏  lsp模块的分辨率设置会导致点击错位  

试了下scale的各种配置情况
1.0: 点击错位
0.0:正常
不填写:模块失效

这样的话能兼顾ba和马娘的分辨率设置吗

**Comment by hexstr** [comment]
什么神奇的游戏，我试了一下别的竖屏游戏都不会出现点击错位的问题。
我看看怎么弄一个为每个App单独设置的东西

**Comment by hexstr** [comment]
好了，试试3.7.2

**Comment by McQck** [comment]
好快的更  感谢

**Comment by McQck** [comment]
![Screenshot_2024-04-04-14-50-26-71_401ec1c63998d4b5eb4c480a9d613a0b](https://github.com/hexstr/UnityFPSUnlocker/assets/104788409/64a58112-1add-4cb9-9f4b-8e7710a3ec65)
![Screenshot_2024-04-04-14-49-37-68_c7ac0966ba589a4bcfaeca6537bedadd](https://github.com/hexstr/UnityFPSUnlocker/assets/104788409/174754a4-ef51-4692-9837-fb42d4c4f9c9)
似乎还是有问题  还是说我设置不对？
通用页面scale设置为0.0的时候也是正常的

ps:不算啥大问题  解决不了也没啥😂

**Comment by hexstr** [comment]
不清楚，问题不大我就不管了233
