### ISSUE TITLE
豎屏使用scale在非預設值時，長按物件並拖曳，物件移動距離大於鼠標實際移動距離

### ISSUE THREAD

**Issue by TermSelf** [nishuoshenme/fgoUnlockFPS#69]
單次點擊位置是正確的，但拖曳會有問題
如果強制改成橫屏之後反而是正常的
版本是3.7.2

另外
scale如果沒有被設置值
UnityFPSUnlocker可能無法被啟用

**Comment by hexstr** [comment]
#67

**Comment by TermSelf** [comment]
關於拖曳的問題，再測試之後發現是我搞錯了，那是遊戲本身造成的BUG
