### ISSUE TITLE
2.1.0版本疑问

### ISSUE THREAD

**Issue by Format-DJ** [nishuoshenme/fgoUnlockFPS#7]
在多种模拟器上使用替换文件的方法会提示l2cpp.文件加载失败导致游戏退出
手机上则正常 请问原因是什么呢？

**Comment by nishuoshenme** [comment]
因为你下载错文件了

**Comment by Format-DJ** [comment]
没有下载错呢 试过v7v8都不可行

**Comment by nishuoshenme** [comment]
> 没有下载错呢 试过v7v8都不可行

嗯...那我也不知道，真的不知道

**Comment by Format-DJ** [comment]
官网的版本么？版本号是？
顺便方便的话可以留个方式打赏吗

**Comment by nishuoshenme** [comment]
> 官网的版本么？版本号是？
> 顺便方便的话可以留个方式打赏吗

一般最新版就是。打赏方式我扔到项目首页了233
