### ISSUE TITLE
是不是不支持崩铁？

### ISSUE THREAD

**Issue by hujhjh9** [nishuoshenme/fgoUnlockFPS#73]
尝试修改后无论是分辨率还是帧数都不起作用
![Screenshot_2024-07-09-01-14-55-005_bin mt plus canary](https://github.com/hexstr/UnityFPSUnlocker/assets/74526779/af0b3d73-e6da-4a99-9e57-3ce9728b08e3)

**Comment by hexstr** [comment]
那应该是不支持
