### ISSUE TITLE
使用Shamiko排除掉游戏还是被检测到了

### ISSUE THREAD

**Issue by Shironaus** [nishuoshenme/fgoUnlockFPS#74]
![Screenshot_20240722-195908](https://github.com/user-attachments/assets/dc9471ad-2ef7-4146-9c69-2a02c013afb6)
用的是3.8的zygisk_module
Android 11
Magisk 27.0
Shamiko 1.0.1

**Comment by hexstr** [comment]
那只能排除掉不加载了，在`custom`中加一个配置，把`fps`设置为`0`

**Comment by Shironaus** [comment]
> 那只能排除掉不加载了，在`custom`中加一个配置，把`fps`设置为`0`
  "custom": {
    "com.nexon.bluearchive": {
      "fps": 0
是这样吗？好像还是会报

**Comment by hexstr** [comment]
你确定日服的包名是带有`nexon`的？你这明明是国际服的

**Comment by Shironaus** [comment]
> 你确定日服的包名是带有标志`nexon`的？你这明明是国际服的

{
  "global": {
    "delay": 300,
    "mod_opcode": true,
    "fps": 90
  },
  "custom": {
    "com.YostarJP.BlueArchive": {
      "fps": 0
    },
    "com.random.package.name.b": {
      "mod_opcode": false
    },
    "com.random.package.name.c": {
      "delay": 300
    },
    "com.random.package.name.d": {
      "description": "keep blank to use global parameters (delete this line)."
    }
  }
}

**Comment by hexstr** [comment]
这样模块应该不会加载了，实在不行就禁用掉模块吧233

**Comment by Shironaus** [comment]
> 这样模块应该不会加载了，最终失败就取消模块吧233

含泪，大哥，我是想用来着，为啥我会被检测到啊

**Comment by hexstr** [comment]
可能反作弊更新了
