### ISSUE TITLE
请问大佬，3.8在模拟器上遇到这个问题

### ISSUE THREAD

**Issue by HolyLight191** [nishuoshenme/fgoUnlockFPS#75]
3.8版本，mumu12模拟器上遇到问题
--------- beginning of main
07-25 02:50:09.534  1306  1307 D UnityFPSUnlocker: [LoadConfig] custom_list: 4
07-25 02:50:09.534  1306  1307 D UnityFPSUnlocker: [LoadConfig] global_cfg:
07-25 02:50:09.534  1306  1307 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1 | scale: -1.000000
07-25 02:50:09.534  1306  1307 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json
07-25 02:50:10.137  1693  1694 D UnityFPSUnlocker: [LoadConfig] custom_list: 4
07-25 02:50:10.137  1693  1694 D UnityFPSUnlocker: [LoadConfig] global_cfg:
07-25 02:50:10.137  1693  1694 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1 | scale: -1.000000
07-25 02:50:10.137  1693  1694 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json
07-25 02:50:22.609  2514  2540 E UnityFPSUnlocker: Cannot open libart.so.

游戏更新以后，就失效了。下面日志是我用app版的，会闪退。
07-25 02:57:57.417  3886  3886 D UnityFPSUnlocker: [UnityFPSUnlocker][xposed] delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 02:57:57.418  3886  3906 D UnityFPSUnlocker: [UnityFPSUnlocker][arm64] Starting...
07-25 02:57:57.418  3886  3906 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 02:58:02.366  3944  3944 D UnityFPSUnlocker: [UnityFPSUnlocker][xposed] delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 02:58:02.366  3944  3968 D UnityFPSUnlocker: [UnityFPSUnlocker][armv7] Starting...
07-25 02:58:02.366  3944  3968 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 02:58:12.132  3944  3952 E UnityFPSUnlocker: Cannot open libart.so.
07-25 02:58:12.367  3944  3968 D UnityFPSUnlocker: ***** begin *****
07-25 02:58:12.368  3944  3968 E UnityFPSUnlocker: SetResolution not fount
07-25 02:58:12.368  3944  3968 D UnityFPSUnlocker: Current resolution: 693x720 @60
07-25 02:58:12.381  3944  3968 D UnityFPSUnlocker: ***** finished *****

**Comment by Shironaus** [comment]
mumu不是能在模拟器调高帧率吗

**Comment by HolyLight191** [comment]
> mumu不是能在模拟器调高帧率吗

调高了，不起效

**Comment by hexstr** [comment]
什么游戏？模拟器是Android几？用旧版模块试试

**Comment by HolyLight191** [comment]
游戏名：＃コンパス
模拟器是Android12
使用3.6.2模块 下面是日志
--------- beginning of main
07-25 13:04:19.104  1691  1695 D UnityFPSUnlocker: [LoadConfig] custom_list: 5
07-25 13:04:19.104  1691  1695 D UnityFPSUnlocker: [LoadConfig] global_cfg:
07-25 13:04:19.104  1691  1695 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1
07-25 13:04:19.104  1691  1695 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json
07-25 13:04:19.114  1694  1694 D UnityFPSUnlocker: xxread (4 != 0)
07-25 13:04:19.114  1694  1694 D UnityFPSUnlocker: xxread (4 != 0)
07-25 13:04:19.114  1694  1694 D UnityFPSUnlocker: xxread (4 != 0)
07-25 13:04:19.114  1694  1694 D UnityFPSUnlocker: xxread (4 != 0)
07-25 13:04:19.147  1694  1739 E UnityFPSUnlocker: Cannot open libart.so.
07-25 13:04:19.175  1758  1761 D UnityFPSUnlocker: [LoadConfig] custom_list: 4
07-25 13:04:19.175  1758  1761 D UnityFPSUnlocker: [LoadConfig] global_cfg:
07-25 13:04:19.175  1758  1761 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1
07-25 13:04:19.175  1758  1761 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json
07-25 13:04:21.826  2524  2524 D UnityFPSUnlocker: [UnityFPSUnlocker][xposed] delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 13:04:21.826  2524  2566 D UnityFPSUnlocker: [UnityFPSUnlocker][armv7] Starting...
07-25 13:04:21.826  2524  2566 D UnityFPSUnlocker:      delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000
07-25 13:04:31.572  2524  2537 E UnityFPSUnlocker: Cannot open libart.so.
07-25 13:04:31.827  2524  2566 D UnityFPSUnlocker: ***** begin *****
07-25 13:04:41.851  2524  2566 E UnityFPSUnlocker: Failed to open libil2cpp.so

**Comment by Shironaus** [comment]
老哥，你开游戏不会报“不明なアプリが検出されたため、終了します。”吗？

**Comment by hexstr** [comment]
搞定，armeabi-v7a的样本还挺罕见，等我整理代码之后更新
![Snipaste_2024-07-28_17-02-33](https://github.com/user-attachments/assets/f6467e8d-05c4-44fa-8c63-26507d101303)

**Comment by HolyLight191** [comment]
谢谢大佬！你是我的神

**Comment by hexstr** [comment]
已发布，试试3.9

**Comment by 775265** [comment]
> 已发布，试试3.9

大佬，3.9测试会导致FGO闪退，回退3.8正常，不知道怎么拿到日志所以没有，抱歉

**Comment by YumeMichi** [comment]
> > 已发布，试试3.9
> 
> 大佬，3.9测试会导致FGO闪退，回退3.8正常，不知道怎么拿到日志所以没有，抱歉

pjsk也会闪退，应该是因为新加的[修改](https://github.com/hexstr/UnityFPSUnlocker/commit/9bca849b663def0da5c92d650e7cd610d978fc95#diff-67df4b12adde13a0feabe4501fc57d4f9d0d2b3903b988aa4b854b8b32bd2985R22)导致的，在pjsk上的函数原型不一样，难不成不同厂商会去魔改这个函数？

魔改了一下不知道写的对不对，至少能正常运行（
https://github.com/YumeMichi/UnityFPSUnlocker/commit/99dc374f5ca48dd5308e58957ec716aeba9bd55c

```
07-29 12:12:15.365 20464 20473 D UnityFPSUnlocker: [UnityFPSUnlocker][arm64] Starting...
07-29 12:12:15.365 20464 20473 D UnityFPSUnlocker:      delay: 3 | fps: 90 | mod_opcode: 1 | scale: 0.800000
07-29 12:12:18.366 20464 20473 D UnityFPSUnlocker: ***** begin *****
07-29 12:12:18.366 20464 20473 D UnityFPSUnlocker: Current resolution: 3168x1440 @120
07-29 12:12:18.366 20464 20473 D UnityFPSUnlocker: Set framerate: 90
07-29 12:12:18.366 20464 20473 D UnityFPSUnlocker: Set resolution: 2534x1152
07-29 12:12:18.366 20464 20473 D UnityFPSUnlocker: ***** finished *****
```

**Comment by hexstr** [comment]
@775265 @YumeMichi 已修复

**Comment by HolyLight191** [comment]
运行良好！

**Comment by NPCACES** [comment]
> 游戏名：＃コンパス 模拟器是Android12 使用3.6.2模块 下面是日志 --------- beginning of main 07-25 13:04:19.104 1691 1695 D UnityFPSUnlocker: [LoadConfig] custom_list: 5 07-25 13:04:19.104 1691 1695 D UnityFPSUnlocker: [LoadConfig] global_cfg: 07-25 13:04:19.104 1691 1695 D UnityFPSUnlocker: delay: 10 | fps: 60 | mod_opcode: 1 07-25 13:04:19.104 1691 1695 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json 07-25 13:04:19.114 1694 1694 D UnityFPSUnlocker: xxread (4 != 0) 07-25 13:04:19.114 1694 1694 D UnityFPSUnlocker: xxread (4 != 0) 07-25 13:04:19.114 1694 1694 D UnityFPSUnlocker: xxread (4 != 0) 07-25 13:04:19.114 1694 1694 D UnityFPSUnlocker: xxread (4 != 0) 07-25 13:04:19.147 1694 1739 E UnityFPSUnlocker: Cannot open libart.so. 07-25 13:04:19.175 1758 1761 D UnityFPSUnlocker: [LoadConfig] custom_list: 4 07-25 13:04:19.175 1758 1761 D UnityFPSUnlocker: [LoadConfig] global_cfg: 07-25 13:04:19.175 1758 1761 D UnityFPSUnlocker: delay: 10 | fps: 60 | mod_opcode: 1 07-25 13:04:19.175 1758 1761 D UnityFPSUnlocker: [Listener::Register] Registered: wd: 1 /data/local/tmp/TargetList.json 07-25 13:04:21.826 2524 2524 D UnityFPSUnlocker: [UnityFPSUnlocker][xposed] delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000 07-25 13:04:21.826 2524 2566 D UnityFPSUnlocker: [UnityFPSUnlocker][armv7] Starting... 07-25 13:04:21.826 2524 2566 D UnityFPSUnlocker: delay: 10 | fps: 60 | mod_opcode: 1 | scale: 1.000000 07-25 13:04:31.572 2524 2537 E UnityFPSUnlocker: Cannot open libart.so. 07-25 13:04:31.827 2524 2566 D UnityFPSUnlocker: ***** begin ***** 07-25 13:04:41.851 2524 2566 E UnityFPSUnlocker: Failed to open libil2cpp.so

这里都能遇见康佬，不过模拟器现在已经支持了高帧打康，不需要安装额外软件
