### ISSUE TITLE
大佬，你能看下我有没有哪里操作错误不

### ISSUE THREAD

**Issue by NPCACES** [nishuoshenme/fgoUnlockFPS#76]
![7456d832-3cdc-4d6f-8045-7f1941738261](https://github.com/user-attachments/assets/b34f68dd-bfd4-4555-bfbd-f59a090492ba)
![4db276c7-bf92-4111-8d03-b6323af2cad9](https://github.com/user-attachments/assets/c75fb010-83d8-457a-ba5c-da8527c19a2c)
游戏名:#ライアリ,它是一个音游，不更改帧数的情况下，在进入游戏以及游戏主界面是30帧，游玩歌曲时是60，我使用的是第三方面具狐狸面具
![5dd08d18-5193-44be-b28d-ffc5da501f5d](https://github.com/user-attachments/assets/4bd9368d-dcd5-4322-83f0-855e15703976)
![90f65ab6-9a1c-41c2-8c38-f8eabeac1623](https://github.com/user-attachments/assets/758fc832-6c73-451e-abe2-5be1e158aa46)

**Comment by NPCACES** [comment]
不好意思，忘记说明设备了，是网易mumu模拟器4.0，安卓版本12

**Comment by hexstr** [comment]
这种在游戏中会自己设置帧率的游戏，你要把`mod_opcode`选项打开

**Comment by NPCACES** [comment]
> 这种在游戏中会自己设置帧率的游戏，你要把`mod_opcode`选项打开

修改为true后进游戏会闪退，该怎么办

**Comment by hexstr** [comment]
看看日志有没有报错的，没有就是游戏有反作弊

**Comment by NPCACES** [comment]
> 看看日志有没有报错的，没有就是游戏有反作弊

呃，如何获取日志

**Comment by NPCACES** [comment]
> 看看日志有没有报错的，没有就是游戏有反作弊

![7C8DA63F929CC870B014C6D8E9241892](https://github.com/user-attachments/assets/de2f994f-2182-47b2-a1c0-50ef6e2088c0)

**Comment by NPCACES** [comment]
> 看看日志有没有报错的，没有就是游戏有反作弊



> > 看看日志有没有报错的，没有就是游戏有反作弊
> 
> ![7C8DA63F929CC870B014C6D8E9241892](https://private-user-images.githubusercontent.com/171557139/355519830-de2f994f-2182-47b2-a1c0-50ef6e2088c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NjAyMTMsIm5iZiI6MTcyMjk1OTkxMywicGF0aCI6Ii8xNzE1NTcxMzkvMzU1NTE5ODMwLWRlMmY5OTRmLTIxODItNDdiMi1hMWMwLTUwZWY2ZTIwODhjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNlQxNTU4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzRiMDE2MmQ4NDI2M2JjZTc1MzU4NDI2OWEwZDc2ODc3N2NjN2MyZDdiNDEwZTRhMGYzMzVjNGUzMGJjMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.887IB-I142Sooxqk0ddKRWll3YZWd8NTZiDJuFy8iz4)

我看了安装包，有这个so文件
![F31AC6FB9A45C0E0F5CC2221FAB3A457](https://github.com/user-attachments/assets/952bcc8f-b793-4da3-b998-6f5d306bfc17)

**Comment by hexstr** [comment]
那应该是我把代码写错了，有时间我测试一下

**Comment by hexstr** [comment]
试了一下模块并没有问题，看来你要自己找原因了，把`delay`调大试试
![Snipaste_2024-08-07_19-27-48](https://github.com/user-attachments/assets/8368b9eb-fa11-424d-931a-f3c8484fb63b)

**Comment by NPCACES** [comment]
> 试了一下模块并没有问题，看来你要自己找原因了，把`delay`调大试试 ![Snipaste_2024-08-07_19-27-48](https://private-user-images.githubusercontent.com/28940831/355795292-8368b9eb-fa11-424d-931a-f3c8484fb63b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwMzg5OTUsIm5iZiI6MTcyMzAzODY5NSwicGF0aCI6Ii8yODk0MDgzMS8zNTU3OTUyOTItODM2OGI5ZWItZmExMS00MjRkLTkzMWEtZjNjODQ4NGZiNjNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDEzNTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxMGQ5YTZiZTRmYmY5ZmIzMmE1MmUwZWJlZWQzNDM3ZGY4OWZkMDZkZDgyZTE0YjIxNzkxMTI0NGNkYTI2MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JBxLUAQ3tq_Bwz9tBHFInJ2mly1ou9ABpBVe0Ypa_VI)

能发下你的json文件让我看下不

**Comment by NPCACES** [comment]
> 试了一下模块并没有问题，看来你要自己找原因了，把`delay`调大试试 ![Snipaste_2024-08-07_19-27-48](https://private-user-images.githubusercontent.com/28940831/355795292-8368b9eb-fa11-424d-931a-f3c8484fb63b.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMwNDE3MDQsIm5iZiI6MTcyMzA0MTQwNCwicGF0aCI6Ii8yODk0MDgzMS8zNTU3OTUyOTItODM2OGI5ZWItZmExMS00MjRkLTkzMWEtZjNjODQ4NGZiNjNiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA3VDE0MzY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOGRiZjU0NGFlNDJkOTdlYTUxMTY3MDQ0NjMwMjRmMTI0ZGE3ODMzYTg0YTY1NDkxOGEyMjVhODIyOWJhNzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ubXyk8cPT2NG5duZh2MN8babccQWF1dY1okpoZNX-PQ)

能发下你的json文件让我看看不，你测试的设备是手机还是模拟器，用的官方原版magisk？

**Comment by hexstr** [comment]
我知道什么情况了，装`LSPosed`然后用`3.7.2`中的`xposed版`吧，这个可以在模拟器上用

**Comment by NPCACES** [comment]
> 我知道什么情况了，装`LSPosed`然后用`3.7.2`中的`xposed版`吧，这个可以在模拟器上用

非常感谢，成功了，这个后续会修复不？

**Comment by hexstr** [comment]
不会
