### ISSUE TITLE
世界計畫 日版 的問題

### ISSUE THREAD

**Issue by Stardusstt** [nishuoshenme/fgoUnlockFPS#80]
遊戲:
com.sega.pjsekai

os:
1.0.22.0.UNNCNXM
(從出廠到最新)

背景:
在K70 Ultra上，在進入譜面的狀況下，fps只能達到115fps(剛好少了5，且他是平均在115)，
我原本覺得應該是遊戲鎖fps(vsync有問題?)，因為在k60u上是正常的，
設成`"fps": 120`，確實調高了限制(選單,60fps->120fps)，但譜面依舊只能115fps，
經過一些測試，發現有開3dmv可以到120(原本是無mv背景，理論上效能要求更低)，
想想問問作者有沒有想法

---

嘗試無效:
* `scene` 鎖120
* 換用`scene fas`
* 設更高，比如`"fps": 144`

---
去mi論壇提bug -> 被歸類其他問題，不回應
問遊戲官方 -> 我們也不知道，沒辦法
🫠

**Comment by hexstr** [comment]
我觉得是你的测试工具出错了

**Comment by Stardusstt** [comment]
用scene跟開發者裡的frame rate tools 都是一樣的，所以才奇怪，而且音游卡會很明顯

**Comment by hexstr** [comment]
那就不知道了，换设备100%解决☝️🤓

**Comment by Stardusstt** [comment]
🫠

**Comment by Stardusstt** [comment]
發現下拉狀態欄會短暫恢復120fps
暫時解決方案->開個小窗放旁邊

這到底是遊戲還是系統的問題😑
