### ISSUE TITLE
启用模块后，红烧天堂/炽焰天穹按键错位

### ISSUE THREAD

**Issue by xiaouex** [nishuoshenme/fgoUnlockFPS#81]
测试了一下，单独对红烧天堂禁用模块，恢复正常，开启模块游戏内的按键错位（不是显示错位，是按的地方错位，也就是直接按按钮logo的地方无效，要偏移几厘米按在空白处才能点击中），怀疑是分辨率的问题尝试修改scale为0.5和0.0（原来默认1.0），无效

**Comment by xiaouex** [comment]
> 测试了一下，单独对红烧天堂禁用模块，恢复正常，开启模块游戏内的按键错位（不是显示错位，是按的地方错位，也就是直接按按钮logo的地方无效，要偏移几厘米按在空白处才能点击中），怀疑是分辨率的问题尝试修改scale为0.5和0.0（原来默认1.0），无效

改scale为0.7，问题暂时解决，就是分辨率的问题，这游戏在不开模块的情况下的分辨率是1024x2140，开了模块1.0x的情况下游戏被强制拉到了1440x3168，所以出现了错位，改成0.7以后游戏分辨率是1008x2217，虽然还是不是游戏原本的分辨率，但是至少按键不错位。
希望加一个scale默认不修改的选项

**Comment by hexstr** [comment]
你写成负数`-1.0`试试

**Comment by xiaouex** [comment]
> 你写成负数`-1.0`试试
有用，感谢
