### ISSUE TITLE
未root 使用lspatch
参数配置不生效

### ISSUE THREAD

**Issue by mayuri0709** [nishuoshenme/fgoUnlockFPS#82]
![IMG_20240921_100309.jpg](https://github.com/user-attachments/assets/13632b7e-8adf-43b0-9c88-97619a4f8811)

![Screenshot_20240921_100602.jpg](https://github.com/user-attachments/assets/a0b2f4ad-7fbc-49c6-aa92-d7dd31b3aa36)

iqooneo８pro
橘子4
已停用游戏魔盒
本机和集成模式打包都不生效
repo旧版config配置有效

**Comment by hexstr** [comment]
那就是LSPatch不支持读取`XSharedPreferences`，你可以用MT管理器把模块的`targetSdkVersion`改成`27`试试

**Comment by mayuri0709** [comment]
如果是指unlocker 的targetSdkVersion
看起來沒效![Screenshot_20241120_153422.jpg](https://github.com/user-attachments/assets/07586a2b-52ef-4f20-9fa8-5bab68cbcc12)
