### ISSUE TITLE
【问题】FPS 值可以设置吗？ 

### ISSUE THREAD

**Issue by hayaokuri** [nishuoshenme/fgoUnlockFPS#83]
例如，可以设置 30、60 和 90，但不能设置 50。

在某些游戏中，40 FPS 不会导致异常行为，但 60 FPS 可能会导致异常行为。
因此最好将其设置为 50 FPS。

第一段视频显示的是正常移动。
第二个视频显示角色不再移动。

https://github.com/user-attachments/assets/13b37773-2643-452e-8a1a-ad4571f4cbe7

https://github.com/user-attachments/assets/cda5560f-ead4-4c68-a379-afae920f9be4

**Comment by hexstr** [comment]
只能设置最大值，不能设置最小值

**Comment by hayaokuri** [comment]
谢谢您的回答！
您说的设置为最大值，是指将 FPS 设置为 50 吗？

对不起，我是初学者。

**Comment by hexstr** [comment]
> 谢谢您的回答！ 您说的设置为最大值，是指将 FPS 设置为 50 吗？
> 
> 对不起，我是初学者。

是的

**Comment by hayaokuri** [comment]
抱歉，我又重复了一遍。

如视频所示，最大值设置为 50。
但在游戏中却设置为 60。

https://github.com/user-attachments/assets/98402af6-dd29-4e2e-9630-bfaa2c964b40

**Comment by hexstr** [comment]
试试`应用信息`->`强制停止`，如果还是不能设置为50，你需要上传运行日志
用这个App捕获日志：https://f-droid.org/repo/com.dp.logcatapp_33.apk

**Comment by hayaokuri** [comment]
还包括不相关的日志。

com.nhnpa.cps 是应用程序名称。

[logcat_10-14-2024_20-58-41.txt](https://github.com/user-attachments/files/17363697/logcat_10-14-2024_20-58-41.txt)

**Comment by hexstr** [comment]
原因可能和Unity Engine自身有关，Unity Engine新版本似乎只能把FPS设置为能和屏幕刷新率整除的数值，比如我的屏幕刷新率为120，那只有30、40、60、120能生效

**Comment by hayaokuri** [comment]
我明白了。
谢谢你回答我的问题。

如果机器翻译难以理解，敬请原谅。
