### ISSUE TITLE
玩碧蓝档案最高只能90帧怎么办？

### ISSUE THREAD

**Issue by sakifuwaa** [nishuoshenme/fgoUnlockFPS#84]
TargetList.json也改成120了，进游戏主界面是有120帧，已进入战斗就会掉到90帧，然后出战斗回到主界面就一直是90帧了。后面改用app，在设置里也都调了120帧，还在单独设置里把ba也专门设置120帧，进游戏还是90帧，请问一下改如何解决呢？
![Screenshot_2024-11-05-00-18-31-764_com omarea vto](https://github.com/user-attachments/assets/2f911d8b-95d9-45e2-9c90-a24788c5aa6a)

**Comment by hexstr** [comment]
在开发者选项中把显示刷新率打开，看看会不会也变成90
![Screenshot_2024-11-05-08-17-50-85_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/user-attachments/assets/0265deb3-d62d-4922-b7c2-b49ef3809a12)

**Comment by sakifuwaa** [comment]
破案了，开了显示刷新率后发现不进入战斗在主页清每日过了一会就从120变成90，估计是开的均衡模式，温度超过42度就会锁90帧，后面打开性能模式，战斗和界面都可以120帧了

**Comment by sakifuwaa** [comment]
小米15，处理器骁龙8e
