### ISSUE TITLE
小米13Pro，HyperOS2，Android15，明日方舟官方服不生效，其他unity游戏起作用

### ISSUE THREAD

**Issue by Cuddly-Red-Fox** [nishuoshenme/fgoUnlockFPS#85]
小米13Pro，HyperOS2，Android15，明日方舟官方服不生效，其他unity游戏起作用，使用KSU刷入了模块，并配置了TargetList.json文件如下
{
  "global": {
    "delay": 5,
    "mod_opcode": true,
    "fps": 120
  },
  "custom": {
    "com.nexon.bluearchive": {
      "fps": 120
    },
    "com.random.package.name.b": {
      "mod_opcode": false
    },
    "com.random.package.name.c": {
      "delay": 5
    },
    "com.hypergryph.arknights": {
    "delay": 10,
    "mod_opcode": true,
    "fps": 120
      
    },
    "com.jutsugames.operator112": {
    "delay": 10,
    "mod_opcode": true,
    "fps": 120
      
    },
    
    "com.random.package.name.d": {
      "description": "keep blank to use global parameters (delete this line)."
    }
  }
}

重启后测试，游戏112接线员（com.jutsugames.operator112）生效120fps
明日方舟（com.hypergryph.arknights）还是锁死60fps，也尝试过使用UnityFPSUnlocker的LSPosed版本，在HyperOS1.0 Android14中，包括之前，对包括明日方舟在内的其余unity游戏都支持120fps，（在禁用云控，温控清除Joyose帧数限制和数据 以及电量电池app数据后）12月5日，明日方舟更新新版本，后手机系统为OS1.0 Android14情况下，使用UnityFPSUnlocker LSPosed版本可正常启用120fps，12月6日晚，接收更新到HyperOS2 Android15，后，发现除明日方舟外，其余几个unity游戏也还可以启用120fps，尝试过scene接管刷新率管理，无效，禁用云控，温控清除Joyose帧数限制和数据 以及电量电池app数据后，依然无效，实在排查不出来是什么导致仅明日方舟锁60帧，（试过卸载重装游戏），可能是云控或者是系统锁死了？但其他游戏又没有影响，而明日方舟本身通过热更新封死帧数上限应该也可能性不是很大（猜测），毕竟12月5日，在系统还是OS1，Android14情况下，明日方舟版本更新后，120fps依然是正常的，希望得到帮助或者是是否有办法解决这个问题，谢谢，看上去这问题很诡异

**Comment by hexstr** [comment]
有没有日志，用logcat抓`adb logcat -s UnityFPSUnlocker`
